### ISSUE TITLE
Copy command documentation from TSTool

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-app-statedmi-doc-user#2]
A number of TSTool commands have been added to StateDMI to provide useful functionality.  The code for these commands implement ***Help*** buttons in the command editors.  The following needs to be done:

1. Implement underlying code to view the Help documentation, similar to TSTool.  A separate issue needs to be added to the StateDMI main repo to address this.
2.  Copy TSTool command documentation to StateDMI user documentation, similar to TSTool.  This involves adding to the command reference section in alphabetical order.  I will need to work with Justin to deploy to the web so that we can test the ***Help*** button links.
3. The StateDMI configuration file needs to contain the URLs for the location of the documentation, similar to TSTool.  TSTool has a system/TSTool.cfg file but StateDMI has not used such a file.  We need to add the file.  This can be done in the installation system folder or a .statedmi folder in user files.  Start with the former and we can discuss whether to take the latter approach similar to newer TSTool.

**Comment by smalers** [comment]
Justin pushed his changes to the master.  I uploaded to Amazon so that the documentation is visible as the online [StateDMI User Documentation](http://learn.openwaterfoundation.org/cdss-app-statedmi-doc-user/).  However, the software is now complaining when using the ***Help*** buttons on dialogs: 

```
Warning[1]:  Unable to display documentation for group "command" and item "WriteTableToDelimitedFile" - no URL formatter defined.
``` 

Justin needs to add some additional code similar to TSTool to make the ***Help*** buttons work.  In TSTool, I have code that the ***Help*** button events call and formats a URL for display.  This is managed through an interface so it can be updated later, for example if the URLs are put into an input file rather than being formed in code.

The online documentation can now be used to take this to the next step.

**Comment by jurentie** [comment]
Added code to update functionality of help button.
See the following [commit in cdss-app-statedmi-main](https://github.com/OpenWaterFoundation/cdss-app-statedmi-main/commit/60e63e9d67e09ace8ac3c39a1c419d48fb5824b3)
